name: slide_container_example
description: Demo of the Slide Container.
publish_to: 'none'

version: 1.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  slide_container:
    path: ../


flutter:
  uses-material-design: true