name: slide_container
description: A container that can be slid vertically and horizontally with a smooth dampened motion. Offers a handful of callbacks for customization.
version: 1.1.2
homepage: https://github.com/quentinleguennec/flutter-slide-container

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
